# docker-compose.yml
# https://docs.docker.com/engine/reference/commandline/compose_up

version: '3.8'
services:

  database:
    image: mysql:8
    container_name: superduper-database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example_root_password
      - MYSQL_USER=example_username
      - MYSQL_PASSWORD=example_password
      - MYSQL_DATABASE=example_database
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql:
