blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/mhaidarhanif/rewinds/discussions/category_choices
    about: Ask questions and discuss with the community
  - name: Visit the site
    url: https://rewinds.mhaidarhanif.com
    about: Check out the examples
